name: Check run
on:
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      # Create check run
      - uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/dtzar/k8s-triage/check-runs
          owner: dtzar
          repo: k8s-triage
          name: "Test check run"
          head_sha: ${{ github.sha }}
          output: |
            title: Test check run title
            summary: A summary of the test check run
            images:
              - alt: Test image
                image_url: https://octodex.github.com/images/jetpacktocat.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Download file
      - uses: octokit/request-action@v2.x
        id: download_file
        with:
          route: GET /repos/dtzar/k8s-triage/README.md
          owner: dtzar
          repo: k8s-triage
          mediaType: |
            format: raw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Update check run to completed, successful status
      - uses: octokit/request-action@v2.x
        id: update_check_run
        with:
          route: PATCH /repos/dtzar/k8s-triage/check-runs/{check_run_id}
          owner: dtzar
          repo: k8s-triage
          check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
          conclusion: "success"
          status: "completed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}